server:
  port: 9190

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes :
        - id : MAGMA-WEATHER
          uri: lb://MAGMA-WEATHER
          predicates:
            - Path=/user/**
        - id : MAGMA-PORTAL
          uri: lb://MAGMA-PORTAL
          predicates :
            - Path=/portal/**


eureka:
  client:
    register-with-eureka:true
    fetch-registry:true
  service-url:
    defaultZone:http://localhost:8761/eureka/
  instance:
    hostname:localhost